title: "Large-Scale Foundation Models: Theory and Practice"
title_short: "Large-Scale FMs"
subtitle1: "EE595B/EE59900B"
semester: "Fall 2025"
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
